name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          pip install --upgrade buildozer cython

      - name: Install Android SDK Components
        run: |
          # Создаем структуру папок
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk
          
          # Устанавливаем cmdline-tools вручную (это база для работы sdkmanager)
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d /tmp/cmdline-tools
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          mv /tmp/cmdline-tools/cmdline-tools/* /home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/latest/
          
          # Принимаем лицензии и устанавливаем build-tools
          export PATH=$PATH:/home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin
          yes | sdkmanager --licenses || true
          sdkmanager "build-tools;33.0.0" "platforms;android-33" "platform-tools"

      - name: Build with Buildozer
        run: |
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
