name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          pip install --upgrade buildozer cython

      - name: Build
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/25.2.9519653
          # ЭТА ПЕРЕМЕННАЯ ЗАПРЕЩАЕТ P4A ЛЕЗТЬ В ИНТЕРНЕТ ЗА SDK
          P4A_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          # Прямой вызов сборки
          buildozer android debug

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
